import React, { useState, useEffect, useCallback } from 'react';
import ReactMarkdown from 'react-markdown';
import './NoteViewer.css';

/**
 * NoteViewer displays Zettelkasten notes in two modes:
 * - Swipe view: Single note at a time with J/K navigation
 * - List view: All notes in sequence
 */
export default function NoteViewer({ notes, sourceTitle, sourceType }) {
  const [viewMode, setViewMode] = useState('swipe'); // 'swipe' or 'list'
  const [currentIndex, setCurrentIndex] = useState(0);

  // Keyboard navigation
  const handleKeyDown = useCallback((e) => {
    if (viewMode !== 'swipe' || !notes?.length) return;

    if (e.key === 'j' || e.key === 'J' || e.key === 'ArrowDown') {
      e.preventDefault();
      setCurrentIndex((prev) => Math.min(prev + 1, notes.length - 1));
    } else if (e.key === 'k' || e.key === 'K' || e.key === 'ArrowUp') {
      e.preventDefault();
      setCurrentIndex((prev) => Math.max(prev - 1, 0));
    }
  }, [viewMode, notes?.length]);

  useEffect(() => {
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [handleKeyDown]);

  // Reset index when notes change
  useEffect(() => {
    setCurrentIndex(0);
  }, [notes]);

  if (!notes || notes.length === 0) {
    return (
      <div className="note-viewer-empty">
        <p>No notes generated yet.</p>
      </div>
    );
  }

  // Ensure currentIndex is within bounds
  const safeIndex = Math.min(currentIndex, notes.length - 1);
  const currentNote = notes[safeIndex];

  // Extra safety check
  if (!currentNote) {
    return (
      <div className="note-viewer-empty">
        <p>Loading notes...</p>
      </div>
    );
  }

  return (
    <div className="note-viewer">
      {/* Header */}
      <div className="note-viewer-header">
        <div className="note-viewer-source">
          {sourceType && (
            <span className={`source-badge source-${sourceType}`}>
              {sourceType === 'youtube' ? 'YouTube' : 'Article'}
            </span>
          )}
          {sourceTitle && <span className="source-title">{sourceTitle}</span>}
        </div>

        <div className="note-viewer-controls">
          <span className="note-count">{notes.length} notes</span>
          <div className="view-toggle">
            <button
              className={`toggle-btn ${viewMode === 'swipe' ? 'active' : ''}`}
              onClick={() => setViewMode('swipe')}
              title="Card view (J/K to navigate)"
            >
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <rect x="4" y="4" width="16" height="16" rx="2" />
              </svg>
            </button>
            <button
              className={`toggle-btn ${viewMode === 'list' ? 'active' : ''}`}
              onClick={() => setViewMode('list')}
              title="List view"
            >
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <line x1="4" y1="6" x2="20" y2="6" />
                <line x1="4" y1="12" x2="20" y2="12" />
                <line x1="4" y1="18" x2="20" y2="18" />
              </svg>
            </button>
          </div>
        </div>
      </div>

      {/* Content */}
      {viewMode === 'swipe' ? (
        <div className="swipe-view">
          <div className="note-card">
            <div className="note-card-header">
              <h3 className="note-title">{currentNote.title}</h3>
              {currentNote.source_model && (
                <span className="note-model" title="Generated by">
                  {currentNote.source_model.split('/').pop()}
                </span>
              )}
            </div>

            {currentNote.tags && currentNote.tags.length > 0 && (
              <div className="note-tags">
                {currentNote.tags.map((tag, i) => (
                  <span key={i} className="note-tag">{tag}</span>
                ))}
              </div>
            )}

            <div className="note-body markdown-content">
              <ReactMarkdown>{currentNote.body}</ReactMarkdown>
            </div>
          </div>

          {/* Navigation */}
          <div className="swipe-navigation">
            <button
              className="nav-btn nav-prev"
              onClick={() => setCurrentIndex((prev) => Math.max(prev - 1, 0))}
              disabled={safeIndex === 0}
            >
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <polyline points="15 18 9 12 15 6" />
              </svg>
            </button>

            <div className="nav-indicator">
              <span className="nav-current">{safeIndex + 1}</span>
              <span className="nav-separator">/</span>
              <span className="nav-total">{notes.length}</span>
            </div>

            <button
              className="nav-btn nav-next"
              onClick={() => setCurrentIndex((prev) => Math.min(prev + 1, notes.length - 1))}
              disabled={safeIndex === notes.length - 1}
            >
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <polyline points="9 18 15 12 9 6" />
              </svg>
            </button>
          </div>

          <p className="nav-hint">
            Press <kbd>J</kbd> / <kbd>K</kbd> or arrow keys to navigate
          </p>
        </div>
      ) : (
        <div className="list-view">
          {notes.map((note, index) => (
            <div key={note.id || index} className="note-list-item">
              <div className="note-list-header">
                <span className="note-number">{index + 1}</span>
                <h3 className="note-title">{note.title}</h3>
                {note.source_model && (
                  <span className="note-model" title="Generated by">
                    {note.source_model.split('/').pop()}
                  </span>
                )}
              </div>

              {note.tags && note.tags.length > 0 && (
                <div className="note-tags">
                  {note.tags.map((tag, i) => (
                    <span key={i} className="note-tag">{tag}</span>
                  ))}
                </div>
              )}

              <div className="note-body markdown-content">
                <ReactMarkdown>{note.body}</ReactMarkdown>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
