import React, { useState } from 'react';
import './Stage1Notes.css';

/**
 * Stage1Notes displays the individual notes generated by each model in Stage 1.
 * Shows a tabbed interface with each model's notes.
 */
export default function Stage1Notes({ responses, labelToModel }) {
  const [activeTab, setActiveTab] = useState(0);

  // Helper to get short model name
  const getModelShortName = (model) => model?.split('/').pop() || model;

  // Get the label for a model (Response A, Response B, etc.)
  const getLabel = (model) => {
    if (!labelToModel) return null;
    for (const [label, m] of Object.entries(labelToModel)) {
      if (m === model) return label;
    }
    return null;
  };

  if (!responses || responses.length === 0) {
    return (
      <div className="stage1-notes empty">
        <p>No model responses available</p>
      </div>
    );
  }

  const activeResponse = responses[activeTab];

  return (
    <div className="stage1-notes">
      <h4>Stage 1: Individual Model Notes</h4>
      <p className="stage-description">
        Each model generated notes independently from the source content.
        These were then anonymized for peer review.
      </p>

      <div className="model-tabs">
        {responses.map((resp, index) => {
          const label = getLabel(resp.model);
          return (
            <button
              key={index}
              className={`model-tab ${activeTab === index ? 'active' : ''}`}
              onClick={() => setActiveTab(index)}
            >
              <span className="model-name">{getModelShortName(resp.model)}</span>
              {label && <span className="model-label">{label.replace('Response ', '')}</span>}
              <span className="note-count">{resp.notes?.length || 0} notes</span>
            </button>
          );
        })}
      </div>

      <div className="notes-content">
        {activeResponse?.notes?.length > 0 ? (
          <div className="mini-notes-grid">
            {activeResponse.notes.map((note, idx) => (
              <div key={idx} className="mini-note-card">
                <span className="note-order-badge">{idx + 1}</span>
                <h5 className="mini-note-title">{note.title}</h5>
                {note.tags && note.tags.length > 0 && (
                  <div className="mini-note-tags">
                    {note.tags.map((tag, tagIdx) => (
                      <span key={tagIdx} className="mini-tag">{tag}</span>
                    ))}
                  </div>
                )}
                <p className="mini-note-body">{note.body}</p>
              </div>
            ))}
          </div>
        ) : (
          <div className="no-notes">
            <p>This model failed to generate notes or returned an error.</p>
            {activeResponse?.raw && (
              <details className="raw-response">
                <summary>View raw response</summary>
                <pre>{activeResponse.raw}</pre>
              </details>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
